In [5]:
import numpy as np 

In [22]:
def init_params(sample_size,lr=0.001,iterations=100):
    losses = []
    params = {}
    grads = {}
    cache = {}
    return sample_size,lr,iterations,params,grads,cache

def init_weights(layers=[3,4,5]):
    n_x = layers[0]
    n_h = layers[1]
    n_y = layers[2]
    W1 = np.random.rand(n_x,n_h)
    W2 = np.random.rand(n_h,n_y)
    b1 = np.zeros(shape=(n_h,1))
    b2 = np.zeros(shape=(n_y,1))
    
    params = {"w1":W1,"b1":b1,"w2":W2,"b2":b2}
    return params

def activation_func(Z,f='sigmoid',derivable=False):
    if f=='sigmoid':
        if derivable:
            A = Z # Aktivasyon fonksiyonu çıktısı
            return A * (1-A)
        else:
            return 1 / (1 + np.exp(-Z)) # Z : lineer fonksiyon cıktısı
    elif f =='tanh':
        if derivable:
            A = Z # Z aslında aktivasyon fonksiyonun çıktısı
            return (1- np.power(A,2))
        else:
            return np.tanh(Z)
        
def lineer_func(X,W,b):
    return np.dot(W,X)+b
        
def forward_propagation(X,params):
    '''
    Args: X: input
          y: real value
          params: weights and biases
    Return: 
          loss: loss
          cache: calculation results z1,a1,z2,a2
    '''
    W1 = params["w1"]
    b1 = params["b1"]
    W2 = params["w2"]
    b2 = params["b2"]

    assert W1.shape[0] ==  X.shape[1]
    #m = self.sample_size # sample_size
    Z1 = lineer_func(X,W1,b1)
    A1 = activation_func(Z1,f='tanh')
    #print("A1.shape:",A1.shape,"W2.shape:",W2.shape)
    assert W2.shape[0] == A1.shape[1]

    Z2 = lineer_func(A1,W2,b2)
    yhat = activation_func(Z2,f='softmax')

    cache = {"Z1":Z1,"A1":A1,"Z2":Z2,"yhat":yhat}

    return yhat,cache       

def calculate_loss(y,yhat):
    loss = -1 * (np.multiply(np.log(yhat),y) + np.multiply(np.log(1-yhat),1-y))
    return loss

def backpropagation():
    return None

def update_params(params,grads,lr=0.001):
    '''
    Returns updated params
    '''
    # Weight and biases 
    W1 = params["w1"]
    b1 = params["b1"]
    W2 = params["w2"]
    b2 = params["b2"]
    #print("W1",W1)
    # Gradients
    dw1 = grads["dw1"]
    db1 = grads["db1"]
    dw2 = grads["dw2"]
    db2 = grads["db2"]
    #print("Dw1:",dw1)
    #print("carpim:",lr*dw1)
    #print("fark:",W1-lr*dw1)
    # Update parameters according to given parameters and learning rate 
    w1 = W1 - lr * dw1
    b1 = b1 - lr * db1
    w2 = W2 - lr * dw2
    b2 = b2 - lr * db2

    updated_params = {"w1":w1,"b1":b1,"w2":w2,"b2":b2}
    return updated_params

In [23]:
sample_size,lr,iterations,params,grads,cache = init_params(120)

In [24]:
params = init_weights()

In [25]:
params

{'w1': array([[0.5435835 , 0.79942741, 0.42102122, 0.18862147],
        [0.54961571, 0.86592759, 0.7472616 , 0.71125533],
        [0.98629582, 0.18245353, 0.20116573, 0.81017015]]),
 'b1': array([[0.],
        [0.],
        [0.],
        [0.]]),
 'w2': array([[0.30909915, 0.93696358, 0.73573113, 0.26251919, 0.33455188],
        [0.76000173, 0.89288701, 0.14840922, 0.92964411, 0.62702954],
        [0.15452959, 0.39500429, 0.23124484, 0.901031  , 0.61553826],
        [0.34996202, 0.57982034, 0.67736167, 0.80482271, 0.34662216]]),
 'b2': array([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])}

In [26]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [27]:
iris_ds = load_iris()
X,y = iris_ds.data,iris_ds.target
print("X.shape:",X.shape,"y.shape:",y.shape)
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,test_size=.2,random_state=3)

print("Xtrain.shape:",Xtrain.shape,"ytrain.shape:",ytrain.shape)
print(f"\nXtrain[:5]:\n{Xtrain[:5]}\n\nytrain[:5]:\n{ytrain[:5]}")





X.shape: (150, 4) y.shape: (150,)
Xtrain.shape: (120, 4) ytrain.shape: (120,)

Xtrain[:5]:
[[5.8 4.  1.2 0.2]
 [4.8 3.4 1.9 0.2]
 [6.9 3.1 5.4 2.1]
 [6.6 2.9 4.6 1.3]
 [4.4 2.9 1.4 0.2]]

ytrain[:5]:
[0 0 2 1 0]


In [28]:
yhat,cache = forward_propagation(Xtrain,params)

ValueError: shapes (3,4) and (120,4) not aligned: 4 (dim 1) != 120 (dim 0)

In [30]:
params["w1"].shape

(3, 4)